config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #,controllers:{
  #  sessions:'users/sessions'
  #}
  # get 'comments/new'
  # get 'comments/create'
  # get 'comments/edit'
  # get 'comments/show'
  # get 'comments/update'
  # get 'comments/index'
  # get 'articles/create'
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/edit'
  # get 'articles/update'
  # get 'articles/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'articles#index'
resources :articles do 
  resources :comments

end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
 
  validates :body, presence:true, length: {minimum: 10}
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :get_article
#####################################################  
  def new
@comment=Comment.new
  end
#####################################################
  def create

    @comment=@article.comments.new comment_params
    @comment.user_id=current_user.id
    if @comment.save
      redirect_to  article_comment_path(@article,@comment), notice: 'Comment successfully created!'
    else 
      render :edit
    end
  end
#####################################################
  def edit
      @comment = @article.comments.find params[:id]

  end
#####################################################
  def show
    @comment = @article.comments.find params[:id]
  end
#####################################################
  def update
@comment=@article.comments.find params[:id]
if @comment.update comment_params

flash[:notice]="Comment successfully updated!"
redirect_to article_comment_path(@article,@comment)
else
  render :edit
end
  end
#####################################################


  def destroy
 @comment=@article.comments.find params[:id]
  if @comment.destroy
    flash[:alert]="Comment successfully deleted!"
  redirect_to  @article
  else 
    render :show
  end
end
#####################################################
  def index
  end
#####################################################
  private
  def comment_params
params.require(:comment).permit(:user_name,:body)
end


  def get_article
@article=Article.find params[:article_id]
  end
#####################################################
end

app/helpers/comments_helper.rb
module CommentsHelper

  def link_for_edit_comment? comment
if current_user
  comment.user_id==current_user.id 
  end

end
end

app/views/comments/_comment_form.html.erb
		<div >
	 <%= render 'shared/errors',object: @comment  %>
<%= form_for ([@article,@comment]) do |f|%>
	<table  >
<tr >
</tr></tr>

<tr><td>comment: </td></tr><tr><td> <%= f.text_area :body, cols:70,rows:6 %></td></tr></tr>

<tr><td >&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;    
 <button type="submit" class="btn btn-primary">Submit</button>
</tr>
</table>
<% end %>


</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<div class="container-fluid">
	
<div class="row">
	
	<div class="col-md-1"></div>
	<div class="col-md-8">
		
		<p>
	<h3>		Edit Comment</h3>
		</p>
<%= render 'comment_form' %>
	</div>
	<div class="col-md-3"></div>
</div>

</div>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<div class="container-fluid">
	
<div class="row">
	
	<div class="col-md-1"></div>
	<div class="col-md-8">
		
		<p>
	<h3>		Add Comment</h3>
		</p>
<%= render 'comment_form' %>
	</div>
	<div class="col-md-3"></div>
</div>

</div>

app/views/comments/show.html.erb
<div class="container-fluid">
	
<div class="row">
	
	<div class="col-md-1"></div>
	<div class="col-md-8">
Title: <br/><%=@article.title %><br/><br/>

Description: <br/><%= truncate(@article.description, length: 35, separator: ' ') %><br/><br/>


<hr>
comment:<br/>
<%= @comment.body%><br/>

<i><%= @comment.user_name %></i> |
<%= @comment.created_at %>
<br/><br/>
 <%= link_to("all comments", @article ) %>
<br/><br/>
<% if link_for_edit_comment? @comment%>
<%= link_to 'Edit comment',edit_article_comment_path(@article,@comment), class: 'btn btn-success' %>
<%= link_to 'Delete comment', article_comment_path(@article,@comment), method: 'delete',class: 'btn btn-success', data: {confirm: 'do you want to delete?'} %>
<% end %>
</div>
	<div class="col-md-3"></div>
</div>

</div>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>