config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #,controllers:{
  #  sessions:'users/sessions'
  #}
  # get 'comments/new'
  # get 'comments/create'
  # get 'comments/edit'
  # get 'comments/show'
  # get 'comments/update'
  # get 'comments/index'
  # get 'articles/create'
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/edit'
  # get 'articles/update'
  # get 'articles/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'articles#index'
resources :articles do 
  resources :comments

end


end

app/models/article.rb
class Article < ApplicationRecord
  
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence:true, length: {minimum: 10}
  validates :description, presence:true, length: {minimum: 10}

  scope :past_articles, ->{where('created_at < ?',Time.now)}

  def get_title 
  title
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]

  #####################################################
  def index
    @articles = Article.all
   
  end
#####################################################  
  def create
      @article = Article.new article_params
      @article.user=current_user
      @article.user_name=current_user.username
 if @article.save
  flash[:notice]="Article successfully created!"
  redirect_to article_path @article
else 
  render 'new'
end
  end
#####################################################
  def new
    @article= Article.new
  end
#####################################################
  def show
    @article =Article.find(params[:id])
    @comments =@article.comments.all
  end
#####################################################
  def edit
@article =Article.find params[:id]
  end
 #####################################################
   def update
    @article =Article.find params[:id]
if @article.update article_params
flash[:notice]="Article successfully updated!"
redirect_to @article
else
  render :edit
end
  end

 ##################################################### 
 def destroy
@article =Article.find params[:id]
@article.destroy
redirect_to articles_path
 end
 ##################################################### 

private
def article_params
params.require(:article).permit(:title,:description,:user_name)
end

end

app/helpers/articles_helper.rb
module ArticlesHelper


def link_for_edit? article

if current_user 
  article.user_id==current_user.id
end
 end


end

app/views/articles/_form.html.erb
<div >
	 <%= render 'shared/errors',object: @article  %>

	
		
<%= form_for(@article) do |f|%>
<table  >


<tr ><td><%= f.label :title %></td></tr>
<tr><td><%= f.text_field :title %></td></tr>
<tr><td><%= f.label :description %></td></tr>
<tr><td><%= f.text_area :description, rows: 6, cols:60 %></td></tr></br>
<tr><td>&nbsp;</td></tr>
<tr><td ><%= f.submit %></td></tr>
</table>
<% end %>


</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/edit.html.erb
<div class="container-fluid">
	
<div class="row">
	
	<div class="col-md-2"></div>
	<div class="col-md-8">
		
		<p>
	<h3>		Edit Article</h3>
		</p>

<%= render 'form' %>
	</div>
	<div class="col-md-2"></div>
</div>

</div>

app/views/articles/index.html.erb
<div class="container-fluid">
	
<div class="row">
	
	<div class="col-md-1"></div>
	<div class="col-md-8">
 <% puts  session[:user_id] %>
<div style='width: 60%; '>
<h3><%=pluralize @articles.count, 'article' %></h3>

<%@articles.each do |article| %>
<p><h3><%= link_to article.title,article %></h3></p> 
<p><%=truncate article.description, length:100,separator: ' ' %></p> 
<p>created by <b> <%=article.user.username%></b> on <i> <%=article.created_at %></i>



</p>

<hr>
<%end%>

</div>
	</div>
	<div class="col-md-3"></div>
</div>

</div>

app/views/articles/new.html.erb
<div class="container-fluid">
	
<div class="row">
	
	<div class="col-md-2"></div>
	<div class="col-md-8">
		
		<p>
	<h3>		Add new Article</h3>
		</p>

<%= render 'form' %>
	</div>
	<div class="col-md-2"></div>
</div>

</div>

app/views/articles/show.html.erb
	

	
	
 <h2><%=@article.title %></h2>

<%= @article.description%><br/><br/>
<br/>
<% if link_for_edit? @article %>
<%= link_to 'Edit article',edit_article_path(@article) %>&nbsp;|
<%= link_to 'Delete article',article_path(@article) ,method: 'delete', data: {confirm: 'do you want to delete?'} %>
<% end %>

<br/>
<hr>
<% @comments.each do |comment| %>
<!-- User.find(comment.user_id).username -->

<i><%= link_to  comment.user.username,article_comment_path(@article,comment) %></i> 
<br/>
<div >
<%= comment.body %><br/>
<br>
<%= comment.created_at %>
<hr>
</div>
<%end %>


<div >

 <br/>

<%= link_to 'add comment',new_article_comment_path(@article), class: 'btn btn-success' %>

	</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>