config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #,controllers:{
  #  sessions:'users/sessions'
  #}
  # get 'comments/new'
  # get 'comments/create'
  # get 'comments/edit'
  # get 'comments/show'
  # get 'comments/update'
  # get 'comments/index'
  # get 'articles/create'
  # get 'articles/new'
  # get 'articles/show'
  # get 'articles/edit'
  # get 'articles/update'
  # get 'articles/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'articles#index'
resources :articles do 
  resources :comments

end


end

app/views/layouts/_flash.html.erb
  <% if flash.any?%>
  <% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>
 <br/>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md fixed-top navbar-light " 
 style="background-color: #d2cdd1;border-bottom: 1px solid white">
  <a class="navbar-brand" href="<%= "#{root_path}" %>">Blog & ROR</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" >
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= "#{root_path}" %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= "#{root_path}" %>" title='to be continued...'>About</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link " href="<%= "#{root_path}" %>" title='to be continued...'>Terms</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
  <div class="logitem" >
   <% if user_signed_in? %>
   <%=  link_to current_user.username,edit_user_registration_path %> &nbsp;&nbsp;|
        <%= link_to 'Sign Out',destroy_user_session_path,method: :delete, class: 'btn btn-lighter' %> 

<% else %>

	<%= link_to 'Sign In',new_user_session_path, class: 'btn btn-lighter' %> | 
    <%= link_to 'Sign Up',new_user_registration_path, class: 'btn btn-lighter' %> 
    <% end %>
</div>
    </form>
  </div>

app/views/layouts/_sidebar.html.erb
<br/><br/>

  <div  id='sidebar' class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical" >
      <a class="nav-link active" id="v-pills-home-tab"  href="<%= "#{articles_path}" %>" role="tab" aria-controls="v-pills-home" aria-selected="true">All Articles</a>
      <% if user_signed_in? %>
      <a class="nav-link" id="v-pills-profile-tab"  href="<%= "#{new_article_path}" %>"  role="tab" aria-controls="v-pills-profile" aria-selected="true">Add New Article</a>
     <% end %>

    
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <div class="container-fluid">
       <row class="row">
         <div col-md-12>
        <%= render 'layouts/header' %>
        </div>
        <br/><br/><br/>
      </row>
           
      <row class="row">

         <div  class=" col-sm-9 col-lg-10" >
          <br/><br/><br/>
                 <%= render 'layouts/flash' %>
          <%= yield %>
         </div>
         <div class=" col-sm-3 col-lg-2"  style="padding-top: 80px;" >
         
            <div  style='border-left: 1px solid white; height: 480px;'>
                 <%= render 'layouts/sidebar' %>
             </div>
         </div> 
         
      </row>
    </div>
  </body>

  <footer>
  <br/><br/>
  <hr>
  <p id='page-footer' style="text-align: center;">
    Copyright &copy; 2020
    <%= link_to 'Blog_&_ROR.com','#' %>
  </p>
</footer>



</html>